import { LifeEvent, FoodPlace } from '../types';

/**
 * Default Vietnamese Life Events:
 * - Official National Holidays (Nghỉ lễ nhà nước Việt Nam)
 * - Traditional Lunar Festivals (Tết, Rằm, Giỗ Tổ Hùng Vương)
 * - Sample Family Birthdays & Death Anniversaries (Ngày Giỗ theo Âm lịch)
 */
export const DEFAULT_LIFE_EVENTS: LifeEvent[] = [
  // 1. Nghỉ lễ Nhà Nước & Lễ Hội Truyền Thống
  {
    id: 'evt_tet_duong',
    title: 'Tết Dương Lịch',
    type: 'holiday',
    isLunar: false,
    day: 1,
    month: 1,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Nghỉ lễ toàn quốc theo quy định nhà nước',
  },
  {
    id: 'evt_tet_nguyen_dan',
    title: 'Tết Nguyên Đán (Mùng 1 Tết Bính Ngọ)',
    type: 'holiday',
    isLunar: true,
    day: 1,
    month: 1,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Tết Cổ Truyền - Sum họp gia đình, chúc Tết ông bà',
  },
  {
    id: 'evt_gio_to_hung_vuong',
    title: 'Giỗ Tổ Hùng Vương (10/3 Âm lịch)',
    type: 'holiday',
    isLunar: true,
    day: 10,
    month: 3,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Nghỉ lễ nhà nước tưởng nhớ các Vua Hùng dựng nước',
  },
  {
    id: 'evt_30_4',
    title: 'Ngày Giải Phóng Miền Nam (30/4)',
    type: 'holiday',
    isLunar: false,
    day: 30,
    month: 4,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Kỷ niệm Ngày Thống nhất Đất nước',
  },
  {
    id: 'evt_01_5',
    title: 'Ngày Quốc Tế Lao Động (01/5)',
    type: 'holiday',
    isLunar: false,
    day: 1,
    month: 5,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Nghỉ lễ toàn quốc',
  },
  {
    id: 'evt_quoc_khanh',
    title: 'Quốc Khánh Nước CHXHCN Việt Nam (02/9)',
    type: 'holiday',
    isLunar: false,
    day: 2,
    month: 9,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Nghỉ lễ Quốc Khánh 2 ngày (2/9 và 3/9)',
  },
  {
    id: 'evt_ram_thang_gieng',
    title: 'Tết Nguyên Tiêu (Rằm tháng Giêng)',
    type: 'family',
    isLunar: true,
    day: 15,
    month: 1,
    repeatYearly: true,
    note: 'Cúng Rằm đầu năm - Lễ Phật cầu an cho cả năm',
  },
  {
    id: 'evt_tet_trung_thu',
    title: 'Tết Trung Thu (Rằm tháng Tám)',
    type: 'family',
    isLunar: true,
    day: 15,
    month: 8,
    repeatYearly: true,
    note: 'Tết thiếu nhi, phá cỗ trông trăng, bánh Trung thu',
  },
  {
    id: 'evt_ong_tao',
    title: 'Tết Táo Quân (23 tháng Chạp)',
    type: 'family',
    isLunar: true,
    day: 23,
    month: 12,
    repeatYearly: true,
    note: 'Cúng tiễn ông Công ông Táo về trời, thả cá chép',
  },

  // 2. Mẫu Ngày Giỗ Tổ Tiên (Tính theo Âm Lịch chuẩn truyền thống)
  {
    id: 'evt_gio_ong_noi',
    title: 'Ngày Giỗ Ông Nội (18/8 Âm lịch)',
    type: 'anniversary_death',
    isLunar: true,
    day: 18,
    month: 8,
    repeatYearly: true,
    personName: 'Ông Nội',
    note: 'Tập trung con cháu tại nhà từ đường, làm mâm cơm cúng',
    reminderDaysBefore: 3,
  },
  {
    id: 'evt_gio_ba_ngoai',
    title: 'Ngày Giỗ Bà Ngoại (06/11 Âm lịch)',
    type: 'anniversary_death',
    isLunar: true,
    day: 6,
    month: 11,
    repeatYearly: true,
    personName: 'Bà Ngoại',
    note: 'Giỗ bà ngoại, chuẩn bị hoa quả, đặt cỗ sớm',
    reminderDaysBefore: 3,
  },

  // 3. Mẫu Sinh Nhật & Kỷ Niệm Gia Đình
  {
    id: 'evt_sn_bo',
    title: 'Sinh nhật Bố',
    type: 'birthday',
    isLunar: false,
    day: 24,
    month: 4,
    repeatYearly: true,
    personName: 'Bố',
    note: 'Tổ chức tiệc gia đình, mua quà tặng bố',
    reminderDaysBefore: 5,
  },
  {
    id: 'evt_sn_me',
    title: 'Sinh nhật Mẹ',
    type: 'birthday',
    isLunar: false,
    day: 15,
    month: 10,
    repeatYearly: true,
    personName: 'Mẹ',
    note: 'Đặt hoa tươi và bánh kem chúc mừng mẹ',
    reminderDaysBefore: 5,
  },
  {
    id: 'evt_sn_vo',
    title: 'Sinh nhật Vợ / Chồng',
    type: 'birthday',
    isLunar: false,
    day: 18,
    month: 9,
    repeatYearly: true,
    personName: 'Vợ/Chồng',
    note: 'Bữa tối lãng mạn, chuẩn bị quà tặng bất ngờ',
    reminderDaysBefore: 7,
  },
  {
    id: 'evt_sn_con',
    title: 'Sinh nhật Con Trai / Con Gái',
    type: 'birthday',
    isLunar: false,
    day: 8,
    month: 6,
    repeatYearly: true,
    personName: 'Con yêu',
    note: 'Tổ chức sinh nhật cho con, mời các bạn bè',
    reminderDaysBefore: 5,
  },
  {
    id: 'evt_ky_niem_cuoi',
    title: 'Kỷ Niệm Ngày Cưới',
    type: 'family',
    isLunar: false,
    day: 12,
    month: 12,
    repeatYearly: true,
    note: 'Kỷ niệm ngày cưới, cùng gia đình đi ăn tối',
    reminderDaysBefore: 5,
  },
];

/**
 * Authentic Vietnamese Food Places & Specialties
 * With accurate GPS coordinates, price ranges, and tags
 */
export const DEFAULT_FOOD_PLACES: FoodPlace[] = [
  // --- KHU ĐÔ THỊ THANH HÀ (CIENCO 5) - CỤM TÒA HH03 KHU B2.1 (SÁT NƠI BẠN ĐANG Ở) ---
  {
    id: 'food_hh03d_pho_bo',
    name: 'Phở Bò Gia Truyền Nam Định - Chân Tòa HH03D Thanh Hà',
    category: 'noodles',
    specialtyDishes: 'Phở bò tái nạm gầu giòn, nước dùng ninh xương ống thơm ngậy, quẩy nóng giòn rụm',
    priceRange: '35.000đ - 50.000đ',
    approxPricePerPerson: 40000,
    address: 'Kiot 06 Chân Tòa HH03D (Khu B2.1), KĐT Thanh Hà Cienco 5, Cự Khê - Phú Lương, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.93021,
    longitude: 105.78443,
    openingHours: '06:00 - 13:30 & 17:30 - 21:30',
    rating: 4.9,
    tags: ['Tòa HH03D', 'B2.1 Thanh Hà', 'Phở bò ngon', 'Ăn sáng', 'Sát chân tòa'],
    note: 'Quán phở quen thuộc của cư dân tòa HH03D, nước dùng trong vắt, ngọt thanh xương ống',
    isFavorite: true,
  },
  {
    id: 'food_hh03d_com_tam',
    name: 'Cơm Tấm Sườn Nướng & Bún Thịt Nướng HH03D',
    category: 'rice',
    specialtyDishes: 'Sườn que ướp mật ong nướng than thơm lừng, chả trứng hấp, bì heo giòn, mỡ hành',
    priceRange: '40.000đ - 55.000đ',
    approxPricePerPerson: 45000,
    address: 'Kiot 16 Chân Tòa HH03D (Khu B2.1), KĐT Thanh Hà Cienco 5, Cự Khê - Phú Lương, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.93018,
    longitude: 105.78445,
    openingHours: '10:00 - 14:00 & 17:00 - 21:00',
    rating: 4.8,
    tags: ['Tòa HH03D', 'B2.1 Thanh Hà', 'Cơm tấm', 'Sườn nướng', 'Ăn trưa & tối'],
    note: 'Sườn cốt lết dày dặn nướng than hoa mềm mọng, nước mắm kẹo pha chuẩn vị Sài Gòn',
    isFavorite: true,
  },
  {
    id: 'food_hh03d_cafe_muoi',
    name: 'Tiệm Cà Phê Muối & Trà Chanh Chân Tòa HH03D',
    category: 'coffee_dessert',
    specialtyDishes: 'Cà phê muối xứ Huế kem béo mặn mà, trà đào cam sả thanh mát, hạt hướng dương',
    priceRange: '20.000đ - 35.000đ',
    approxPricePerPerson: 25000,
    address: 'Kiot 02 Chân Tòa HH03D (Khu B2.1), KĐT Thanh Hà Cienco 5, Cự Khê - Phú Lương, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.93025,
    longitude: 105.78440,
    openingHours: '06:30 - 23:00',
    rating: 4.9,
    tags: ['Tòa HH03D', 'B2.1 Thanh Hà', 'Cà phê muối', 'Trà chanh', 'Ngồi vỉa hè thoáng'],
    note: 'Không gian vỉa hè chân tòa lộng gió, điểm tụ tập chuyện trò thư giãn của cư dân HH03',
    isFavorite: true,
  },
  {
    id: 'food_hh03c_bun_ca_cay',
    name: 'Bún Cá Cay Hải Phòng & Bún Ốc Tòa HH03C',
    category: 'noodles',
    specialtyDishes: 'Cá rô phi chiên giòn tan, chả cá thu mỏng dai, dọc mùng giòn sần sật, nước dùng chua cay',
    priceRange: '35.000đ - 50.000đ',
    approxPricePerPerson: 40000,
    address: 'Kiot 11 Chân Tòa HH03C (Khu B2.1), KĐT Thanh Hà Cienco 5, Cự Khê - Phú Lương, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.92974,
    longitude: 105.78445,
    openingHours: '06:00 - 14:00',
    rating: 4.7,
    tags: ['Tòa HH03C', 'B2.1 Thanh Hà', 'Bún cá cay', 'Bún ốc', 'Sát vách HH03D'],
    note: 'Cách tòa HH03D chỉ 50 mét, cá chiên tươi mới mỗi sáng, ốc nhồi béo ngậy',
    isFavorite: true,
  },
  {
    id: 'food_hh03e_lau_nuong',
    name: 'Lẩu Nướng Than Hoa Không Khói B2.1 Thanh Hà',
    category: 'hotpot_bbq',
    specialtyDishes: 'Ba chỉ bò Mỹ cuộn nấm, nầm nướng sốt me chua ngọt, lẩu Thái tomyum hải sản chua cay',
    priceRange: '120.000đ - 180.000đ/người',
    approxPricePerPerson: 150000,
    address: 'Kiot 08 Tòa HH03E (Khu B2.1), KĐT Thanh Hà Cienco 5, Cự Khê - Phú Lương, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.93067,
    longitude: 105.78442,
    openingHours: '10:30 - 14:00 & 16:30 - 23:00',
    rating: 4.8,
    tags: ['Tòa HH03E', 'B2.1 Thanh Hà', 'Lẩu nướng', 'Tụ tập liên hoan', 'Gia đình'],
    note: 'Cách tòa HH03D 60 mét, hệ thống hút khói âm hiện đại, đồ ăn tươi ngon đầy đặn',
    isFavorite: true,
  },
  {
    id: 'food_hh03b_banh_mi_chao',
    name: 'Bánh Mì Chảo & Xôi Xéo Cô Lan Tòa HH03B',
    category: 'casual',
    specialtyDishes: 'Bánh mì chảo sốt bơ tỏi pate trứng lòng đào, xôi xéo vàng ươm mỡ hành ruốc thịt',
    priceRange: '25.000đ - 45.000đ',
    approxPricePerPerson: 35000,
    address: 'Kiot 03 Tòa HH03B (Khu B2.1), KĐT Thanh Hà Cienco 5, Cự Khê - Phú Lương, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.92930,
    longitude: 105.78447,
    openingHours: '06:00 - 13:00',
    rating: 4.8,
    tags: ['Tòa HH03B', 'B2.1 Thanh Hà', 'Bánh mì chảo', 'Xôi xéo', 'Ăn sáng'],
    note: 'Pate nhà làm thơm nức béo ngậy, bánh mì nướng nóng giòn tan',
    isFavorite: false,
  },
  // --- KHU ĐÔ THỊ THANH HÀ CÁC CỤM KHÁC (B1.4, HỒ ĐIỀU HÒA) ---
  {
    id: 'food_thanhha_pho_cu_tang',
    name: 'Phở Cụ Tặng - Bò Tái Lăn & Gầu Giòn Thanh Hà',
    category: 'noodles',
    specialtyDishes: 'Phở bò tái lăn áp chảo thơm nức, gầu giòn vàng ươm, quẩy nóng giòn',
    priceRange: '35.000đ - 55.000đ',
    approxPricePerPerson: 45000,
    address: 'Kiot 08 Tòa HH02-2A, Khu Đô Thị Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9492,
    longitude: 105.8078,
    openingHours: '06:00 - 13:30 & 17:30 - 21:00',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'Phở bò ngon', 'Ăn sáng', 'Giá bình dân'],
    note: 'Quán phở quen thuộc của cư dân chung cư HH02 Thanh Hà, nước dùng hầm xương ngọt thanh không mì chính',
    isFavorite: true,
  },
  {
    id: 'food_thanhha_buncha_que',
    name: 'Bún Chả Que Tre Nướng Than Hoa Thanh Hà',
    category: 'noodles',
    specialtyDishes: 'Chả que tre nướng than hoa thơm lừng, nem cua bể giòn tan, dưa góp chua ngọt',
    priceRange: '35.000đ - 50.000đ',
    approxPricePerPerson: 40000,
    address: 'Kiot 12 Tòa HH01C, Khu Đô Thị Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9525,
    longitude: 105.8095,
    openingHours: '09:30 - 14:00 & 17:00 - 20:30',
    rating: 4.7,
    tags: ['KĐT Thanh Hà', 'Bún chả que tre', 'Ăn trưa', 'Bình dân'],
    note: 'Chả băm kẹp que tre nướng hoa than hồng rực, nước mắm ấm nóng vừa vặn',
    isFavorite: true,
  },
  {
    id: 'food_thanhha_comnieu_laucuadong',
    name: 'Cơm Niêu Sing & Lẩu Cua Đồng Hồ Thanh Hà',
    category: 'rice',
    specialtyDishes: 'Cơm niêu cháy giòn sốt bò tiêu đen, lẩu riêu cua đồng bắp bò sườn sụn',
    priceRange: '75.000đ - 160.000đ/người',
    approxPricePerPerson: 95000,
    address: 'Ven Hồ Điều Hòa B2.1, Khu Đô Thị Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9465,
    longitude: 105.8062,
    openingHours: '10:00 - 22:30',
    rating: 4.9,
    tags: ['KĐT Thanh Hà', 'View hồ thoáng mát', 'Gia đình', 'Đỗ xe thoải mái'],
    note: 'View hồ sinh thái Thanh Hà cực đẹp và thoáng gió, cơm niêu giòn 2 mặt, lẩu riêu cua nguyên chất thơm ngậy',
    isFavorite: true,
  },
  {
    id: 'food_thanhha_bundau_met',
    name: 'Bún Đậu Mắm Tôm Mẹt Chân Cầu Thanh Hà',
    category: 'noodles',
    specialtyDishes: 'Mẹt bún đậu thập cẩm: chả cốm giòn nóng, dồi sụn chiên, lòng non luộc, mắm tôm đánh sủi bọt',
    priceRange: '35.000đ - 60.000đ',
    approxPricePerPerson: 45000,
    address: 'Liền kề B1.4 LK23, Khu Đô Thị Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9510,
    longitude: 105.8115,
    openingHours: '09:00 - 21:00',
    rating: 4.7,
    tags: ['KĐT Thanh Hà', 'Bún đậu mắm tôm', 'Ăn trưa', 'Bình dân'],
    note: 'Đậu mơ rán vàng giòn ruột mềm mướt, mắm tôm nguyên chất Thanh Hóa pha chanh ớt',
  },
  {
    id: 'food_thanhha_gamet_lonmuong',
    name: 'Gà Mẹt & Lợn Mường Mắc Khén - Thanh Hà Quán',
    category: 'hotpot_bbq',
    specialtyDishes: 'Mẹt gà đồi 7 món (nướng lu, hấp lá chanh, xào lăn), lợn mường nướng chao, xôi nếp nương',
    priceRange: '130.000đ - 220.000đ/người',
    approxPricePerPerson: 160000,
    address: 'Khu A2.4 Liền Kề 06, KĐT Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9450,
    longitude: 105.8045,
    openingHours: '10:00 - 23:00',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'Gà đồi 7 món', 'Tụ họp bạn bè', 'Bia hơi & Mồi bén'],
    note: 'Gà ta thả đồi thịt chắc ngọt không bở, hạt dổi mắc khén Tây Bắc chấm muối ớt chanh chuẩn bài',
    isFavorite: true,
  },
  {
    id: 'food_thanhha_banhcuon_caobang',
    name: 'Bánh Cuốn Nóng Cao Bằng & Trứng Lòng Đào',
    category: 'casual',
    specialtyDishes: 'Bánh cuốn tráng tay nóng hổi chấm nước canh xương ống hầm ngọt lịm, trứng hấp lòng đào',
    priceRange: '30.000đ - 45.000đ',
    approxPricePerPerson: 35000,
    address: 'Kiot 05 Tòa HH02-1C, Khu Đô Thị Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9485,
    longitude: 105.8088,
    openingHours: '06:00 - 13:00',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'Bánh cuốn canh', 'Ăn sáng ngon', 'Bình dân'],
    note: 'Nước canh hầm từ xương tủy ngọt lịm kèm giò nấm, măng ngâm ớt quả mắc mật chuẩn vị vùng cao',
  },
  {
    id: 'food_thanhha_kafa_cafe_ho',
    name: 'Kafa Cafe & The Coffee House Ven Hồ Thanh Hà',
    category: 'coffee_dessert',
    specialtyDishes: 'Cà phê cốt dừa Hải Phòng, trà đào cam sả, bạc xỉu kem béo ngậy',
    priceRange: '28.000đ - 55.000đ',
    approxPricePerPerson: 38000,
    address: 'Đảo Tròn Công Viên Hồ Thanh Hà B2.1, KĐT Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9470,
    longitude: 105.8070,
    openingHours: '06:30 - 23:00',
    rating: 4.9,
    tags: ['KĐT Thanh Hà', 'View hồ hoàng hôn', 'Cà phê gió mát', 'Check-in'],
    note: 'Không gian mở ven hồ điều hòa Thanh Hà lộng gió, ngắm hoàng hôn chiều tuyệt đẹp',
    isFavorite: true,
  },
  {
    id: 'food_thanhha_haisan_biendong',
    name: 'Hải Sản Tươi Sống Đại Dương Xanh - Thanh Hà',
    category: 'seafood',
    specialtyDishes: 'Cua Cà Mau hấp bia, tôm sú nướng muối ớt, lẩu hải sản chua cay thập cẩm',
    priceRange: '180.000đ - 320.000đ/người',
    approxPricePerPerson: 220000,
    address: 'Đường đôi Trục Nam Hà Tây, KĐT Thanh Hà (gần vòng xuyến B1.1), Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9478,
    longitude: 105.8105,
    openingHours: '10:00 - 23:00',
    rating: 4.7,
    tags: ['KĐT Thanh Hà', 'Hải sản bơi bể', 'Gia đình', 'Đỗ ô tô'],
    note: 'Hải sản chọn sống tại bể cân tại chỗ chế biến theo yêu cầu, tươi ngon giá hợp lý',
  },
  {
    id: 'food_thanhha_bbq_launuong',
    name: 'Lẩu Nướng Không Khói BBQ Thanh Hà',
    category: 'hotpot_bbq',
    specialtyDishes: 'Ba chỉ bò Mỹ cuộn nấm, nầm nướng chao, lẩu Thái Tomyum hải sản chua cay',
    priceRange: '139.000đ - 199.000đ/người',
    approxPricePerPerson: 160000,
    address: 'Khu B1.1 Liền Kề 02, KĐT Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9540,
    longitude: 105.8120,
    openingHours: '11:00 - 14:00 & 17:00 - 23:00',
    rating: 4.6,
    tags: ['KĐT Thanh Hà', 'Lẩu nướng', 'Bạn bè tụ tập', 'Buffet'],
    note: 'Thịt bò tươi ướp sốt đậm đà, vỉ nướng không khói hiện đại, quầy buffet line tự chọn',
  },
  {
    id: 'food_thanhha_chaosuo_banhmi',
    name: 'Cháo Sườn Sụn & Bánh Mì Chảo Cô Hương',
    category: 'casual',
    specialtyDishes: 'Cháo sườn sụn sánh mịn quẩy ruốc, bánh mì chảo pate trứng lòng đào xúc xích bốc khói',
    priceRange: '25.000đ - 45.000đ',
    approxPricePerPerson: 35000,
    address: 'Chân Tòa HH03A, Khu Đô Thị Thanh Hà, Cự Khê, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9435,
    longitude: 105.8050,
    openingHours: '06:00 - 21:30',
    rating: 4.7,
    tags: ['KĐT Thanh Hà', 'Cháo sườn sụn', 'Bánh mì chảo', 'Bình dân'],
    note: 'Cháo nấu từ bột gạo xay nhuyễn ngọt tự nhiên từ xương, sườn sụn giòn sần sật',
  },

  // --- KHU VỰC LÂN CẬN THANH HÀ: KIẾN HƯNG, XA LA, VĂN PHÚ, HÀ ĐÔNG ---
  {
    id: 'food_xala_vit_vandinh',
    name: 'Vịt Cỏ Vân Đình & Lẩu Vịt Om Sấu - Phúc La Xa La',
    category: 'hotpot_bbq',
    specialtyDishes: 'Vịt nướng than hoa da giòn thịt ngọt, lẩu vịt om sấu khoai sọ bùi béo chua thanh',
    priceRange: '100.000đ - 160.000đ/người',
    approxPricePerPerson: 125000,
    address: 'Đường Phúc La - Văn Phú (gần Viện 103 & Xa La), Q. Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9580,
    longitude: 105.7920,
    openingHours: '10:00 - 22:30',
    rating: 4.8,
    tags: ['Gần Thanh Hà', 'Xa La', 'Vịt cỏ Vân Đình', 'Lẩu vịt om sấu'],
    note: 'Cách Thanh Hà chỉ ~1.8km, vịt cỏ thả đồng thơm béo, nước chấm tỏi ớt đặc sánh',
    isFavorite: true,
  },
  {
    id: 'food_vanphu_bunbo_nguyen',
    name: 'Bún Bò Huế Ngự Uyển - KĐT Văn Phú',
    category: 'noodles',
    specialtyDishes: 'Tô bún bò Huế đặc biệt móng giò, bò bắp hoa, chả cua, tiết mềm, nước dùng cay nồng ruốc sả',
    priceRange: '45.000đ - 65.000đ',
    approxPricePerPerson: 55000,
    address: 'TT37 Ô 15 KĐT Văn Phú (gần ngã tư Lacasta), P. Phú La, Q. Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9615,
    longitude: 105.7725,
    openingHours: '06:00 - 21:00',
    rating: 4.8,
    tags: ['Gần Thanh Hà', 'Văn Phú', 'Bún bò Huế', 'Chất lượng cao'],
    note: 'Hương vị bún bò chuẩn Huế, ớt chưng thơm cay xé lưỡi, rau sống hoa chuối tươi ngon',
    isFavorite: true,
  },
  {
    id: 'food_xala_laucuadong_68',
    name: 'Lẩu Cua Đồng 68 - KĐT Xa La Hà Đông',
    category: 'hotpot_bbq',
    specialtyDishes: 'Nồi lẩu riêu cua đồng bắp bò hoa chuối giòn ngọt, đậu rán lướt ván, trứng vịt lộn',
    priceRange: '120.000đ - 180.000đ/người',
    approxPricePerPerson: 145000,
    address: 'BT04 Lô 12 KĐT Xa La, Phường Phúc La, Quận Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9620,
    longitude: 105.7950,
    openingHours: '10:30 - 22:30',
    rating: 4.7,
    tags: ['Gần Thanh Hà', 'Xa La', 'Lẩu cua đồng', 'Đỗ ô tô thoải mái'],
    note: 'Gạch cua đồng giã tay đóng bánh dày cộp, nước dùng chua dịu từ dấm bỗng nếp truyền thống',
  },
  {
    id: 'food_hadong_boto_quanmoc',
    name: 'Bò Tơ Quán Mộc - Chi Nhánh Hà Đông',
    category: 'hotpot_bbq',
    specialtyDishes: 'Bò tơ cuốn bánh tráng rau rừng, bò tơ nướng tảng cháy cạnh, dải bò nướng y',
    priceRange: '160.000đ - 260.000đ/người',
    approxPricePerPerson: 200000,
    address: 'KĐT Văn Quán / Đường Nguyễn Văn Lộc, Q. Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9780,
    longitude: 105.7890,
    openingHours: '10:00 - 22:30',
    rating: 4.9,
    tags: ['Hà Đông', 'Bò tơ cuốn', 'Gia đình', 'Tiếp khách'],
    note: 'Không gian phố xưa Hà Nội hoài niệm, thịt bò tơ non mềm mọng nước',
    isFavorite: true,
  },
  {
    id: 'food_hadong_traungon_letrongtan',
    name: 'Trâu Ngon Quán - KĐT An Hưng, Lê Trọng Tấn',
    category: 'fine_dining',
    specialtyDishes: 'Thịt trâu nhúng mẻ thanh mát, trâu xào lá lốt, trâu nướng tảng thơm lừng',
    priceRange: '180.000đ - 300.000đ/người',
    approxPricePerPerson: 220000,
    address: 'Khu Đô Thị An Hưng, Đường Lê Trọng Tấn, Q. Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9765,
    longitude: 105.7535,
    openingHours: '10:00 - 22:00',
    rating: 4.8,
    tags: ['Hà Đông', 'Đặc sản thịt trâu', 'Sân vườn rộng lớn', 'Đỗ 100 ô tô'],
    note: 'Nhà hàng quy mô hàng nghìn m2, chế biến hơn 108 món trâu tươi giật nóng sốt',
  },
  {
    id: 'food_linhdam_vitquay_bacthao',
    name: 'Vịt Quay Bắc Kinh & Lẩu Thái Hải Sản - Bán Đảo Linh Đàm',
    category: 'hotpot_bbq',
    specialtyDishes: 'Vịt quay da giòn bóng bẩy, lẩu Thái tomyum chua cay đậm đà',
    priceRange: '110.000đ - 190.000đ/người',
    approxPricePerPerson: 150000,
    address: 'Khu Biệt Thự TT4 Bán Đảo Linh Đàm, P. Hoàng Liệt, Q. Hoàng Mai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9705,
    longitude: 105.8280,
    openingHours: '10:00 - 22:30',
    rating: 4.7,
    tags: ['Gần Thanh Hà', 'Linh Đàm', 'Vịt quay', 'View hồ thoáng mát'],
    note: 'Cách Thanh Hà ~3.5km, không gian ven hồ Linh Đàm rợp bóng cây xanh',
  },

  // --- TRUNG TÂM HÀ NỘI (HOÀN KIẾM, HAI BÀ TRƯNG, ĐỐNG ĐA) ---
  {
    id: 'food_pho_thin',
    name: 'Phở Thìn Lò Đúc',
    category: 'noodles',
    specialtyDishes: 'Phở bò tái lăn trứ danh, nhiều hành hoa thơm nồng',
    priceRange: '70.000đ - 90.000đ',
    approxPricePerPerson: 80000,
    address: '13 Lò Đúc, P. Phạm Đình Hổ, Q. Hai Bà Trưng, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0186,
    longitude: 105.8576,
    openingHours: '06:00 - 21:00',
    rating: 4.8,
    tags: ['Nổi tiếng', 'Phở gia truyền', 'Đậm đà'],
    note: 'Thịt bò xào tái lăn áp chảo lửa lớn thơm nức, ăn kèm quẩy giòn',
    isFavorite: true,
  },
  {
    id: 'food_pho_bat_dan',
    name: 'Phở Bát Đàn Gia Truyền',
    category: 'noodles',
    specialtyDishes: 'Phở bò tái nạm, tái gầu nước dùng trong veo ngọt thanh',
    priceRange: '60.000đ - 85.000đ',
    approxPricePerPerson: 70000,
    address: '49 Bát Đàn, P. Cửa Đông, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0345,
    longitude: 105.8468,
    openingHours: '06:00 - 10:00 & 18:00 - 20:30',
    rating: 4.7,
    tags: ['Phố cổ', 'Gia truyền', 'Ăn sáng'],
    note: 'Nét văn hóa xếp hàng quen thuộc của người Hà Nội',
    isFavorite: true,
  },
  {
    id: 'food_buncha_dackim',
    name: 'Bún Chả Đắc Kim Hàng Mành',
    category: 'noodles',
    specialtyDishes: 'Bún chả nướng than hoa thơm lừng & nem cua bể giòn rụm',
    priceRange: '70.000đ - 120.000đ',
    approxPricePerPerson: 90000,
    address: 'Số 1 Hàng Mành, P. Hàng Gai, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0329,
    longitude: 105.8492,
    openingHours: '08:30 - 21:30',
    rating: 4.6,
    tags: ['Bún chả', 'Nem cua bể', 'Đặc sản Hà Nội'],
    note: 'Phần chả rất nhiều thịt, nước chấm ấm nóng chua ngọt thanh',
  },
  {
    id: 'food_chaca_thanglong',
    name: 'Chả Cá Thăng Long',
    category: 'seafood',
    specialtyDishes: 'Chả cá Lăng nướng nghệ chảo nóng, thì là & hành hoa',
    priceRange: '160.000đ - 250.000đ/người',
    approxPricePerPerson: 190000,
    address: '6B Đường Thành, P. Cửa Đông, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0336,
    longitude: 105.8465,
    openingHours: '10:30 - 21:30',
    rating: 4.9,
    tags: ['Đặc sản', 'Gia đình', 'Đỗ xe ô tô'],
    note: 'Không gian nhà cổ lịch sự, cá mềm thơm không tanh, mắm tôm ngon',
    isFavorite: true,
  },
  {
    id: 'food_bundau_ngotram',
    name: 'Bún Đậu Mắm Tôm Ngõ Trạm',
    category: 'noodles',
    specialtyDishes: 'Mẹt bún đậu thập cẩm: chả cốm giòn, dồi sụn, thịt luộc',
    priceRange: '45.000đ - 70.000đ',
    approxPricePerPerson: 55000,
    address: '1B Ngõ Trạm, P. Hàng Bông, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0319,
    longitude: 105.8461,
    openingHours: '09:00 - 15:30',
    rating: 4.7,
    tags: ['Bình dân', 'Mắm tôm thơm', 'Ăn trưa'],
    note: 'Đậu mơ rán lướt ván ngoài giòn trong mềm, mắm tôm đánh sủi bọt ngậy',
  },
  {
    id: 'food_launam_ashima',
    name: 'Lẩu Nấm Thiên Nhiên Ashima',
    category: 'hotpot_bbq',
    specialtyDishes: 'Nước dùng lẩu nấm bổ dưỡng, nấm tùng nhung & bò Wagyu',
    priceRange: '300.000đ - 550.000đ/người',
    approxPricePerPerson: 380000,
    address: '182 Triệu Việt Vương, P. Bùi Thị Xuân, Q. Hai Bà Trưng, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0116,
    longitude: 105.8505,
    openingHours: '10:30 - 22:00',
    rating: 4.9,
    tags: ['Cao cấp', 'Tiếp khách', 'Gia đình', 'Tốt cho sức khỏe'],
    note: 'Không gian sang trọng yên tĩnh, nước dùng nấm thanh ngọt đỉnh cao',
    isFavorite: true,
  },
  {
    id: 'food_cafe_giang',
    name: 'Cà Phê Trứng Giảng',
    category: 'coffee_dessert',
    specialtyDishes: 'Cà phê trứng nóng hổi béo ngậy, cacao trứng',
    priceRange: '35.000đ - 55.000đ',
    approxPricePerPerson: 40000,
    address: '39 Nguyễn Hữu Huân, P. Lý Thái Tổ, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0348,
    longitude: 105.8541,
    openingHours: '07:00 - 22:30',
    rating: 4.8,
    tags: ['Cà phê trứng', 'Phố cổ', 'Check-in'],
    note: 'Cụ Giảng là người sáng tạo món cà phê trứng từ năm 1946',
  },
  {
    id: 'food_comnieu_thuynga',
    name: 'Cơm Niêu Thúy Nga',
    category: 'rice',
    specialtyDishes: 'Cơm niêu cháy giòn, cá bống kho tộ, canh cua cà pháo',
    priceRange: '130.000đ - 250.000đ/người',
    approxPricePerPerson: 180000,
    address: '110B2 Nguyễn Chí Thanh, P. Láng Hạ, Q. Đống Đa, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0211,
    longitude: 105.8118,
    openingHours: '10:00 - 21:30',
    rating: 4.6,
    tags: ['Cơm gia đình', 'Đỗ xe ô tô', 'Tiếp khách'],
    note: 'Cơm niêu đập cháy 2 mặt thơm giòn rụm, cá kho đậm đà đưa cơm',
  },

  // --- TP. HỒ CHÍ MINH ---
  {
    id: 'food_comtam_baghien',
    name: 'Cơm Tấm Ba Ghiền',
    category: 'rice',
    specialtyDishes: 'Miếng sườn nướng khổng lồ che kín đĩa cơm, chả trứng, bì',
    priceRange: '65.000đ - 110.000đ',
    approxPricePerPerson: 85000,
    address: '84 Đặng Văn Ngữ, Phường 10, Q. Phú Nhuận, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7937,
    longitude: 106.6715,
    openingHours: '07:30 - 21:00',
    rating: 4.8,
    tags: ['Sườn khổng lồ', 'Nổi tiếng', 'Michelin Bib Gourmand'],
    note: 'Sườn ướp mật ong nướng than hoa mềm mọng nước, hương vị đặc trưng Sài Gòn',
    isFavorite: true,
  },
  {
    id: 'food_pho_le',
    name: 'Phở Lệ Nguyễn Trãi',
    category: 'noodles',
    specialtyDishes: 'Phở bò thập cẩm, tái nạm gầu gân bò viên giòn sần sật',
    priceRange: '75.000đ - 95.000đ',
    approxPricePerPerson: 85000,
    address: '415 Nguyễn Trãi, Phường 7, Quận 5, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7554,
    longitude: 106.6698,
    openingHours: '06:00 - 01:00 (đêm)',
    rating: 4.8,
    tags: ['Phở Sài Gòn', 'Ăn đêm', 'Michelin Guide'],
    note: 'Nước dùng ngọt đậm đà từ xương ống hầm kỹ, bò viên tự làm rất ngon',
    isFavorite: true,
  },
  {
    id: 'food_banhmi_huynhhoa',
    name: 'Bánh Mì Huỳnh Hoa',
    category: 'casual',
    specialtyDishes: 'Bánh mì pate bơ chả giò ngập tràn nhân nặng nửa ký',
    priceRange: '65.000đ - 85.000đ',
    approxPricePerPerson: 70000,
    address: '26 Lê Thị Riêng, P. Bến Thành, Quận 1, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7712,
    longitude: 106.6917,
    openingHours: '11:00 - 21:00',
    rating: 4.6,
    tags: ['Bánh mì ô môi', 'Nổi tiếng', 'Siêu nhiều thịt'],
    note: 'Pate béo ngậy quết dày, ăn nửa ổ là no căng bụng',
  },
  {
    id: 'food_pizza_4ps',
    name: "Pizza 4P's Bến Thành",
    category: 'casual',
    specialtyDishes: 'Pizza phô mai Burrata tươi nhà làm, mỳ Ý sốt cua đặc biệt',
    priceRange: '200.000đ - 380.000đ/người',
    approxPricePerPerson: 280000,
    address: '8 Thủ Khoa Huân, P. Bến Thành, Quận 1, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7738,
    longitude: 106.6978,
    openingHours: '10:00 - 22:30',
    rating: 4.9,
    tags: ['Hẹn hò', 'Gia đình', 'Phô mai tươi', 'Dịch vụ chuẩn Nhật'],
    note: 'Nên đặt bàn trước qua ứng dụng hoặc hotline vào cuối tuần',
    isFavorite: true,
  },
  {
    id: 'food_dimtutac',
    name: 'Dim Tu Tac - Ẩm Thực Quảng Đông',
    category: 'fine_dining',
    specialtyDishes: 'Há cảo tôm thủy tinh, xíu mại gạch cua, vịt quay Bắc Kinh',
    priceRange: '250.000đ - 480.000đ/người',
    approxPricePerPerson: 350000,
    address: '29B Trần Cao Vân, Phường 6, Quận 3, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7842,
    longitude: 106.6961,
    openingHours: '10:00 - 22:00',
    rating: 4.8,
    tags: ['Dimsum', 'Tiếp khách', 'Gia đình', 'Đỗ xe thoải mái'],
    note: 'Dimsum tươi nóng hổi nặn tay trong ngày, vị thanh tinh tế chuẩn vị',
  },
  {
    id: 'food_lauga_lae',
    name: 'Lẩu Gà Lá É Tao Ngộ',
    category: 'hotpot_bbq',
    specialtyDishes: 'Lẩu gà đồi lá é cay nồng ớt xiêm xanh & nấm bào ngư',
    priceRange: '180.000đ - 280.000đ/nồi',
    approxPricePerPerson: 120000,
    address: '79 Trần Huy Liệu, Phường 12, Q. Phú Nhuận, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7915,
    longitude: 106.6782,
    openingHours: '10:00 - 22:00',
    rating: 4.7,
    tags: ['Lẩu ngon', 'Bạn bè tụ tập', 'Hương vị Đà Lạt'],
    note: 'Lá é the cay thơm lừng kích thích vị giác, nước lẩu ngọt thanh từ gà ta',
  },

  // --- ĐÀ NẴNG ---
  {
    id: 'food_miquang_bamua',
    name: 'Mì Quảng Bà Mua',
    category: 'noodles',
    specialtyDishes: 'Mì Quảng ếch, mì Quảng tôm thịt cắn kèm ớt xanh giòn',
    priceRange: '35.000đ - 60.000đ',
    approxPricePerPerson: 45000,
    address: '95A Nguyễn Tri Phương, Q. Thanh Khê, Đà Nẵng',
    city: 'Đà Nẵng',
    latitude: 16.0592,
    longitude: 108.2045,
    openingHours: '06:30 - 21:30',
    rating: 4.7,
    tags: ['Đặc sản Đà Nẵng', 'Rau sống bắp chuối', 'Bánh tráng mè'],
    note: 'Sợi mì vàng óng dai mềm, chan nước nhưn đậm đà vừa phải',
    isFavorite: true,
  },
  {
    id: 'food_banhtrang_tran',
    name: 'Bánh Tráng Cuốn Thịt Heo Đại Lộc - Quán Trần',
    category: 'casual',
    specialtyDishes: 'Thịt heo hai đầu da luộc mỏng cuốn rau rừng & mắm nêm',
    priceRange: '120.000đ - 180.000đ/phần',
    approxPricePerPerson: 150000,
    address: '04 Lê Duẩn, Q. Hải Châu, Đà Nẵng',
    city: 'Đà Nẵng',
    latitude: 16.0718,
    longitude: 108.2212,
    openingHours: '09:00 - 22:00',
    rating: 4.8,
    tags: ['Thịt heo 2 đầu da', 'Mắm nêm trứ danh', 'Máy lạnh'],
    note: 'Đĩa rau sống hơn 10 loại tươi rói, mắm nêm giã tỏi ớt thơm lừng',
  },
];
