import { LifeEvent, FoodPlace } from '../types';

/**
 * Default Vietnamese Life Events:
 * - Official National Holidays (Nghỉ lễ nhà nước Việt Nam)
 * - Traditional Lunar Festivals (Tết, Rằm, Giỗ Tổ Hùng Vương)
 * - Sample Family Birthdays & Death Anniversaries (Ngày Giỗ theo Âm lịch)
 */
export const DEFAULT_LIFE_EVENTS: LifeEvent[] = [
  // 1. Nghỉ lễ Nhà Nước & Lễ Hội Truyền Thống
  {
    id: 'evt_tet_duong',
    title: 'Tết Dương Lịch',
    type: 'holiday',
    isLunar: false,
    day: 1,
    month: 1,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Nghỉ lễ toàn quốc theo quy định nhà nước',
  },
  {
    id: 'evt_tet_nguyen_dan',
    title: 'Tết Nguyên Đán (Mùng 1 Tết Bính Ngọ)',
    type: 'holiday',
    isLunar: true,
    day: 1,
    month: 1,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Tết Cổ Truyền - Sum họp gia đình, chúc Tết ông bà',
  },
  {
    id: 'evt_gio_to_hung_vuong',
    title: 'Giỗ Tổ Hùng Vương (10/3 Âm lịch)',
    type: 'holiday',
    isLunar: true,
    day: 10,
    month: 3,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Nghỉ lễ nhà nước tưởng nhớ các Vua Hùng dựng nước',
  },
  {
    id: 'evt_30_4',
    title: 'Ngày Giải Phóng Miền Nam (30/4)',
    type: 'holiday',
    isLunar: false,
    day: 30,
    month: 4,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Kỷ niệm Ngày Thống nhất Đất nước',
  },
  {
    id: 'evt_01_5',
    title: 'Ngày Quốc Tế Lao Động (01/5)',
    type: 'holiday',
    isLunar: false,
    day: 1,
    month: 5,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Nghỉ lễ toàn quốc',
  },
  {
    id: 'evt_quoc_khanh',
    title: 'Quốc Khánh Nước CHXHCN Việt Nam (02/9)',
    type: 'holiday',
    isLunar: false,
    day: 2,
    month: 9,
    repeatYearly: true,
    isNationalHoliday: true,
    note: 'Nghỉ lễ Quốc Khánh 2 ngày (2/9 và 3/9)',
  },
  {
    id: 'evt_ram_thang_gieng',
    title: 'Tết Nguyên Tiêu (Rằm tháng Giêng)',
    type: 'family',
    isLunar: true,
    day: 15,
    month: 1,
    repeatYearly: true,
    note: 'Cúng Rằm đầu năm - Lễ Phật cầu an cho cả năm',
  },
  {
    id: 'evt_tet_trung_thu',
    title: 'Tết Trung Thu (Rằm tháng Tám)',
    type: 'family',
    isLunar: true,
    day: 15,
    month: 8,
    repeatYearly: true,
    note: 'Tết thiếu nhi, phá cỗ trông trăng, bánh Trung thu',
  },
  {
    id: 'evt_ong_tao',
    title: 'Tết Táo Quân (23 tháng Chạp)',
    type: 'family',
    isLunar: true,
    day: 23,
    month: 12,
    repeatYearly: true,
    note: 'Cúng tiễn ông Công ông Táo về trời, thả cá chép',
  },

  // 2. Mẫu Ngày Giỗ Tổ Tiên (Tính theo Âm Lịch chuẩn truyền thống)
  {
    id: 'evt_gio_ong_noi',
    title: 'Ngày Giỗ Ông Nội (18/8 Âm lịch)',
    type: 'anniversary_death',
    isLunar: true,
    day: 18,
    month: 8,
    repeatYearly: true,
    personName: 'Ông Nội',
    note: 'Tập trung con cháu tại nhà từ đường, làm mâm cơm cúng',
    reminderDaysBefore: 3,
  },
  {
    id: 'evt_gio_ba_ngoai',
    title: 'Ngày Giỗ Bà Ngoại (06/11 Âm lịch)',
    type: 'anniversary_death',
    isLunar: true,
    day: 6,
    month: 11,
    repeatYearly: true,
    personName: 'Bà Ngoại',
    note: 'Giỗ bà ngoại, chuẩn bị hoa quả, đặt cỗ sớm',
    reminderDaysBefore: 3,
  },

  // 3. Mẫu Sinh Nhật & Kỷ Niệm Gia Đình
  {
    id: 'evt_sn_bo',
    title: 'Sinh nhật Bố',
    type: 'birthday',
    isLunar: false,
    day: 24,
    month: 4,
    repeatYearly: true,
    personName: 'Bố',
    note: 'Tổ chức tiệc gia đình, mua quà tặng bố',
    reminderDaysBefore: 5,
  },
  {
    id: 'evt_sn_me',
    title: 'Sinh nhật Mẹ',
    type: 'birthday',
    isLunar: false,
    day: 15,
    month: 10,
    repeatYearly: true,
    personName: 'Mẹ',
    note: 'Đặt hoa tươi và bánh kem chúc mừng mẹ',
    reminderDaysBefore: 5,
  },
  {
    id: 'evt_sn_vo',
    title: 'Sinh nhật Vợ / Chồng',
    type: 'birthday',
    isLunar: false,
    day: 18,
    month: 9,
    repeatYearly: true,
    personName: 'Vợ/Chồng',
    note: 'Bữa tối lãng mạn, chuẩn bị quà tặng bất ngờ',
    reminderDaysBefore: 7,
  },
  {
    id: 'evt_sn_con',
    title: 'Sinh nhật Con Trai / Con Gái',
    type: 'birthday',
    isLunar: false,
    day: 8,
    month: 6,
    repeatYearly: true,
    personName: 'Con yêu',
    note: 'Tổ chức sinh nhật cho con, mời các bạn bè',
    reminderDaysBefore: 5,
  },
  {
    id: 'evt_ky_niem_cuoi',
    title: 'Kỷ Niệm Ngày Cưới',
    type: 'family',
    isLunar: false,
    day: 12,
    month: 12,
    repeatYearly: true,
    note: 'Kỷ niệm ngày cưới, cùng gia đình đi ăn tối',
    reminderDaysBefore: 5,
  },
];

/**
 * Authentic Vietnamese Food Places & Specialties
 * With accurate GPS coordinates, price ranges, and tags
 */
export const DEFAULT_FOOD_PLACES: FoodPlace[] = [
  // --- KHU VỰC KĐT THANH HÀ (ĐỊA CHỈ & TÊN QUÁN CHUẨN XÁC 100% TRÊN GOOGLE MAPS) ---
  {
    id: 'food_giaothuy_thanhha',
    name: 'Nhà Hàng Hải Sản Giao Thủy',
    category: 'seafood',
    specialtyDishes: 'Hải sản tươi sống bơi bể: Cua Cà Mau hấp sả, tôm sú nướng muối ớt, cá tầm, mực nhảy',
    priceRange: '150.000đ - 350.000đ/người',
    approxPricePerPerson: 250000,
    address: 'B1.4-LK16 Số Nhà 15 Khu Đô Thị Thanh Hà B, Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9348,
    longitude: 105.7876,
    openingHours: '10:00 - 23:30',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'Hải sản tươi sống', 'B1.4-LK16', 'Gia đình'],
    note: 'Nhà hàng hải sản tươi sống quy mô lớn bậc nhất KĐT Thanh Hà, bãi đỗ ô tô rộng rãi',
    isFavorite: true,
  },
  {
    id: 'food_thanhha_foods',
    name: 'Thanh Hà Foods',
    category: 'casual',
    specialtyDishes: 'Pizza hải sản phô mai kéo sợi, mỳ Ý bò băm sốt cà chua, hamburger bò, bánh mì chảo',
    priceRange: '35.000đ - 90.000đ',
    approxPricePerPerson: 65000,
    address: 'Tòa HH02-1B Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9315,
    longitude: 105.7892,
    openingHours: '08:00 - 22:30',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'HH02-1B', 'Pizza & Fastfood', 'Trẻ em & Gia đình'],
    note: 'Thương hiệu ẩm thực quen thuộc chân tòa HH02-1B Thanh Hà, có website và giao tận nhà',
    isFavorite: true,
  },
  {
    id: 'food_comtam_thanhha',
    name: 'Cơm Tấm Thanh Hà',
    category: 'rice',
    specialtyDishes: 'Cơm tấm sườn bì chả nướng than hoa, canh rong biển thanh mát, trứng ốp la lòng đào',
    priceRange: '35.000đ - 55.000đ',
    approxPricePerPerson: 45000,
    address: 'B2.1 LK03-04 Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9312,
    longitude: 105.7860,
    openingHours: '09:00 - 21:00',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'B2.1', 'Cơm tấm sườn nướng', 'Ăn trưa & tối'],
    note: 'Quán cơm tấm nổi tiếng tại khu liền kề B2.1 Thanh Hà, sườn nướng mật ong mềm ngậy',
    isFavorite: true,
  },
  {
    id: 'food_buncatuelam_thanhha',
    name: 'Bún Cá Tuệ Lâm',
    category: 'noodles',
    specialtyDishes: 'Bún cá rô phi chiên giòn rụm, chả cá thác lác thơm nức, nước dùng chua thanh thanh',
    priceRange: '35.000đ - 50.000đ',
    approxPricePerPerson: 40000,
    address: 'Kiot 12 Tòa HH03B Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.929296,
    longitude: 105.784470,
    openingHours: '06:00 - 14:00 & 17:00 - 21:00',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'HH03B', 'Bún cá rô phi', 'Ăn sáng'],
    note: 'Quán bún cá nổi tiếng tại kiot 12 chân tòa HH03B Thanh Hà, cá rán giòn tan nước dùng đậm đà',
    isFavorite: true,
  },
  {
    id: 'food_banhcuon_hh021b',
    name: 'Bánh Cuốn Nóng & Bún Các Món',
    category: 'noodles',
    specialtyDishes: 'Bánh cuốn tráng tay nóng hổi nhân thịt mộc nhĩ, chả quế nướng than hoa, bún mọc sườn',
    priceRange: '30.000đ - 45.000đ',
    approxPricePerPerson: 35000,
    address: 'Kiot 10 Tòa HH02-1B Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9316,
    longitude: 105.7893,
    openingHours: '06:00 - 13:30',
    rating: 4.7,
    tags: ['KĐT Thanh Hà', 'HH02-1B', 'Bánh cuốn nóng', 'Ăn sáng'],
    note: 'Bánh cuốn nóng tráng tại chỗ thơm ngậy hành phi giòn rụm',
    isFavorite: true,
  },
  {
    id: 'food_aha_cafe_thanhha',
    name: 'Aha Cafe Thanh Hà',
    category: 'coffee_dessert',
    specialtyDishes: 'Cà phê cốt dừa truyền thống, trà đào cam sả, bạc xỉu kem ngậy, sinh tố xoài',
    priceRange: '25.000đ - 50.000đ',
    approxPricePerPerson: 35000,
    address: 'B1.4 LK9 Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9358,
    longitude: 105.7882,
    openingHours: '06:30 - 23:00',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'B1.4 LK9', 'Aha Cafe', 'Gặp gỡ bạn bè'],
    note: 'Quán cà phê thương hiệu Aha mặt tiền rộng rãi, ngắm đường phố KĐT Thanh Hà',
    isFavorite: true,
  },
  {
    id: 'food_king_coffee_thanhha',
    name: 'King Coffee Thanh Hà',
    category: 'coffee_dessert',
    specialtyDishes: 'Cà phê rang xay nguyên chất, espresso, trà hoa quả nhiệt đới, kem đá xay',
    priceRange: '28.000đ - 55.000đ',
    approxPricePerPerson: 40000,
    address: 'Tòa HH02 Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9305,
    longitude: 105.7888,
    openingHours: '07:00 - 23:00',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'HH02', 'View hồ & cá Koi', 'Không gian gỗ sang trọng'],
    note: 'Không gian nhà gỗ độc đáo tầng 1 có hồ cá Koi thư thái, tầng 2 thoáng đãng view hồ',
    isFavorite: true,
  },
  {
    id: 'food_nhahang_thanhha',
    name: 'Nhà Hàng Thanh Hà',
    category: 'fine_dining',
    specialtyDishes: 'Đặc sản đồng quê: gà đồi hấp lá chanh, lẩu cua đồng bắp bò, cá nướng than hoa, ngỗng 7 món',
    priceRange: '130.000đ - 250.000đ/người',
    approxPricePerPerson: 180000,
    address: 'Biệt Thự Ven Hồ B2.1 BT09-17 Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9325,
    longitude: 105.7865,
    openingHours: '09:30 - 23:00',
    rating: 4.8,
    tags: ['KĐT Thanh Hà', 'B2.1 Ven Hồ', 'Đặt tiệc liên hoan', 'Gia đình'],
    note: 'Biệt thự ẩm thực ven hồ thoáng mát chuyên phục vụ liên hoan, gia đình và đặt tiệc tại KĐT Thanh Hà',
    isFavorite: true,
  },
  {
    id: 'food_hoangtuan_bunrieu',
    name: 'Hoàng Tuấn - Bún Riêu Bề Bề',
    category: 'noodles',
    specialtyDishes: 'Bún riêu cua bề bề bắp bò, bánh cuốn nóng chả quế, giò tai giòn sần sật',
    priceRange: '35.000đ - 55.000đ',
    approxPricePerPerson: 45000,
    address: 'Kiot 44 Tòa HH01C Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.933808,
    longitude: 105.791725,
    openingHours: '06:00 - 14:00 & 17:30 - 21:00',
    rating: 4.7,
    tags: ['KĐT Thanh Hà', 'HH01C', 'Bún riêu bề bề', 'Ăn sáng'],
    note: 'Quán bún riêu cua đồng kết hợp bề bề tươi ngọt đậm đà nức tiếng tòa HH01C Thanh Hà',
    isFavorite: true,
  },
  {
    id: 'food_banhcanh_anhhai',
    name: 'Bánh Canh Cá Lóc Anh Hai',
    category: 'noodles',
    specialtyDishes: 'Bánh canh bột gạo cá lóc đồng rim nghệ cay nồng, đầu cá béo ngậy',
    priceRange: '35.000đ - 50.000đ',
    approxPricePerPerson: 42000,
    address: 'LKB1.4 LK06 Khu Đô Thị Thanh Hà, Cự Khê, Thanh Oai, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9350,
    longitude: 105.7880,
    openingHours: '06:30 - 21:30',
    rating: 4.7,
    tags: ['KĐT Thanh Hà', 'B1.4 LK06', 'Bánh canh cá lóc', 'Hương vị miền Trung'],
    note: 'Bánh canh cá lóc chuẩn vị miền Trung, cá lóc đồng rim thơm phức đậm vị',
  },

  // --- CÁC QUÁN ĂN NỔI TIẾNG KHU VỰC LÂN CẬN (HÀ ĐÔNG, VĂN PHÚ, KIẾN HƯNG, XA LA) ---
  {
    id: 'food_hadong_comnieu_kombo',
    name: 'Kombo - Cơm Niêu Singapore',
    category: 'rice',
    specialtyDishes: 'Cơm niêu bò nướng tiêu đen giòn rụm 2 mặt, cơm niêu gà sốt nấm đậm đà',
    priceRange: '70.000đ - 110.000đ',
    approxPricePerPerson: 85000,
    address: 'TT37 Ô 10 KĐT Văn Phú, Phường Phú La, Quận Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9635,
    longitude: 105.7740,
    openingHours: '10:00 - 14:00 & 17:30 - 21:30',
    rating: 4.8,
    tags: ['KĐT Văn Phú', 'Hà Đông', 'Cơm niêu Singapore', 'Gia đình'],
    note: 'Cơm cháy vàng rụm 2 mặt độc quyền, nước sốt rưới xèo xèo thơm phức',
    isFavorite: true,
  },
  {
    id: 'food_vanphu_bunbo_nguyen',
    name: 'Bún Bò Huế Ngự Uyển',
    category: 'noodles',
    specialtyDishes: 'Tô bún bò Huế đặc biệt móng giò, bò bắp hoa, chả cua, tiết mềm, nước dùng cay nồng ruốc sả',
    priceRange: '45.000đ - 65.000đ',
    approxPricePerPerson: 55000,
    address: 'TT37 Ô 15 KĐT Văn Phú, Phường Phú La, Quận Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9615,
    longitude: 105.7725,
    openingHours: '06:00 - 21:00',
    rating: 4.8,
    tags: ['Văn Phú', 'Hà Đông', 'Bún bò Huế chuẩn vị'],
    note: 'Hương vị bún bò chuẩn Huế, ớt chưng thơm cay xé lưỡi, rau sống hoa chuối tươi ngon',
    isFavorite: true,
  },
  {
    id: 'food_hadong_boto_quanmoc',
    name: 'Bò Tơ Quán Mộc',
    category: 'hotpot_bbq',
    specialtyDishes: 'Bò tơ cuốn bánh tráng rau rừng, bò tơ nướng tảng cháy cạnh, dải bò nướng y',
    priceRange: '160.000đ - 260.000đ/người',
    approxPricePerPerson: 200000,
    address: '14 BT7 KĐT Văn Quán, Đường Nguyễn Văn Lộc, Phường Mộ Lao, Quận Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9850,
    longitude: 105.7870,
    openingHours: '10:00 - 22:30',
    rating: 4.9,
    tags: ['Hà Đông', 'Văn Quán', 'Bò tơ cuốn', 'Gia đình', 'Tiếp khách'],
    note: 'Không gian phố xưa Hà Nội hoài niệm, thịt bò tơ non mềm mọng nước',
    isFavorite: true,
  },
  {
    id: 'food_hadong_traungon_hacau',
    name: 'Trâu Ngon Quán',
    category: 'fine_dining',
    specialtyDishes: 'Thịt trâu tươi 108 món: trâu nhúng mẻ, trâu cháy tỏi, trâu cuốn cải, lẩu trâu tươi',
    priceRange: '180.000đ - 320.000đ/người',
    approxPricePerPerson: 230000,
    address: 'Số 02 Lê Hồng Phong, Phường Hà Cầu, Quận Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9702,
    longitude: 105.7765,
    openingHours: '10:00 - 22:30',
    rating: 4.9,
    tags: ['Hà Đông', 'Hà Cầu', 'Trâu Ngon Quán chính hãng', '108 món trâu'],
    note: 'Cơ sở chính thức của hệ thống Trâu Ngon Quán tại Hà Đông, không gian cực kỳ rộng rãi',
    isFavorite: true,
  },
  {
    id: 'food_xala_vit_vandinh',
    name: 'Vịt Cỏ Vân Đình',
    category: 'hotpot_bbq',
    specialtyDishes: 'Vịt nướng than hoa da giòn thịt ngọt, lẩu vịt om sấu khoai sọ bùi béo chua thanh',
    priceRange: '100.000đ - 160.000đ/người',
    approxPricePerPerson: 125000,
    address: 'BT04 Lô 10 KĐT Xa La, Phường Phúc La, Quận Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9580,
    longitude: 105.7920,
    openingHours: '10:00 - 22:30',
    rating: 4.8,
    tags: ['Xa La', 'Hà Đông', 'Vịt cỏ Vân Đình', 'Lẩu vịt om sấu'],
    note: 'Vịt cỏ thả đồng thơm béo, nước chấm tỏi ớt đặc sánh',
    isFavorite: true,
  },
  {
    id: 'food_hadong_lau_halinh',
    name: 'Lẩu Cua Sông - Hà Linh Quán',
    category: 'hotpot_bbq',
    specialtyDishes: 'Lẩu cua sông bắp bò, ngỗng 10 món, cá sông Đà, gà đồi và lợn bản nướng',
    priceRange: '130.000đ - 220.000đ/người',
    approxPricePerPerson: 165000,
    address: 'Ô 98 TT20 KĐT Văn Phú, Phường Phú La, Quận Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9630,
    longitude: 105.7735,
    openingHours: '10:00 - 22:30',
    rating: 4.8,
    tags: ['Văn Phú', 'Hà Đông', 'Lẩu cua sông', 'Gia đình'],
    note: 'Nhà hàng ẩm thực đồng quê nổi tiếng, cách Thanh Hà ~3.5km, đỗ xe rộng rãi',
    isFavorite: true,
  },
  {
    id: 'food_kienhung_lauduoibo_hanhno',
    name: 'Lẩu Đuôi Bò Hạnh Nổ',
    category: 'hotpot_bbq',
    specialtyDishes: 'Lẩu đuôi bò om thuốc bắc thanh ngọt, bò tơ nướng ngũ vị, lòng bò xào khế',
    priceRange: '120.000đ - 200.000đ/người',
    approxPricePerPerson: 150000,
    address: 'Liền kề 13 Lô 19 Khu đấu giá Mậu Lương, P. Kiến Hưng, Q. Hà Đông, Hà Nội',
    city: 'Hà Nội',
    latitude: 20.9520,
    longitude: 105.7980,
    openingHours: '10:00 - 23:00',
    rating: 4.8,
    tags: ['Kiến Hưng', 'Gần Thanh Hà', 'Lẩu đuôi bò', 'Tụ họp'],
    note: 'Quán lẩu đuôi bò nức tiếng khu Kiến Hưng - Mậu Lương ngay sát KĐT Thanh Hà',
    isFavorite: true,
  },

  // --- TRUNG TÂM HÀ NỘI (HOÀN KIẾM, HAI BÀ TRƯNG, ĐỐNG ĐA) ---
  {
    id: 'food_pho_thin',
    name: 'Phở Thìn Lò Đúc',
    category: 'noodles',
    specialtyDishes: 'Phở bò tái lăn trứ danh, nhiều hành hoa thơm nồng',
    priceRange: '70.000đ - 90.000đ',
    approxPricePerPerson: 80000,
    address: '13 Lò Đúc, P. Phạm Đình Hổ, Q. Hai Bà Trưng, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0186,
    longitude: 105.8576,
    openingHours: '06:00 - 21:00',
    rating: 4.8,
    tags: ['Nổi tiếng', 'Phở gia truyền', 'Đậm đà'],
    note: 'Thịt bò xào tái lăn áp chảo lửa lớn thơm nức, ăn kèm quẩy giòn',
    isFavorite: true,
  },
  {
    id: 'food_pho_bat_dan',
    name: 'Phở Bát Đàn',
    category: 'noodles',
    specialtyDishes: 'Phở bò tái nạm, tái gầu nước dùng trong veo ngọt thanh',
    priceRange: '60.000đ - 85.000đ',
    approxPricePerPerson: 70000,
    address: '49 Bát Đàn, P. Cửa Đông, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0345,
    longitude: 105.8468,
    openingHours: '06:00 - 10:00 & 18:00 - 20:30',
    rating: 4.7,
    tags: ['Phố cổ', 'Gia truyền', 'Ăn sáng'],
    note: 'Nét văn hóa xếp hàng quen thuộc của người Hà Nội',
    isFavorite: true,
  },
  {
    id: 'food_buncha_dackim',
    name: 'Bún Chả Đắc Kim',
    category: 'noodles',
    specialtyDishes: 'Bún chả nướng than hoa thơm lừng & nem cua bể giòn rụm',
    priceRange: '70.000đ - 120.000đ',
    approxPricePerPerson: 90000,
    address: 'Số 1 Hàng Mành, P. Hàng Gai, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0329,
    longitude: 105.8492,
    openingHours: '08:30 - 21:30',
    rating: 4.6,
    tags: ['Bún chả', 'Nem cua bể', 'Đặc sản Hà Nội'],
    note: 'Phần chả rất nhiều thịt, nước chấm ấm nóng chua ngọt thanh',
  },
  {
    id: 'food_chaca_thanglong',
    name: 'Chả Cá Thăng Long',
    category: 'seafood',
    specialtyDishes: 'Chả cá Lăng nướng nghệ chảo nóng, thì là & hành hoa',
    priceRange: '160.000đ - 250.000đ/người',
    approxPricePerPerson: 190000,
    address: '6B Đường Thành, P. Cửa Đông, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0336,
    longitude: 105.8465,
    openingHours: '10:30 - 21:30',
    rating: 4.9,
    tags: ['Đặc sản', 'Gia đình', 'Đỗ xe ô tô'],
    note: 'Không gian nhà cổ lịch sự, cá mềm thơm không tanh, mắm tôm ngon',
    isFavorite: true,
  },
  {
    id: 'food_bundau_ngotram',
    name: 'Bún Đậu Mắm Tôm Ngõ Trạm',
    category: 'noodles',
    specialtyDishes: 'Mẹt bún đậu thập cẩm: chả cốm giòn, dồi sụn, thịt luộc',
    priceRange: '45.000đ - 70.000đ',
    approxPricePerPerson: 55000,
    address: '1B Ngõ Trạm, P. Hàng Bông, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0319,
    longitude: 105.8461,
    openingHours: '09:00 - 15:30',
    rating: 4.7,
    tags: ['Bình dân', 'Mắm tôm thơm', 'Ăn trưa'],
    note: 'Đậu mơ rán lướt ván ngoài giòn trong mềm, mắm tôm đánh sủi bọt ngậy',
  },
  {
    id: 'food_launam_ashima',
    name: 'Lẩu Nấm Ashima',
    category: 'hotpot_bbq',
    specialtyDishes: 'Nước dùng lẩu nấm bổ dưỡng, nấm tùng nhung & bò Wagyu',
    priceRange: '300.000đ - 550.000đ/người',
    approxPricePerPerson: 380000,
    address: '182 Triệu Việt Vương, P. Bùi Thị Xuân, Q. Hai Bà Trưng, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0116,
    longitude: 105.8505,
    openingHours: '10:30 - 22:00',
    rating: 4.9,
    tags: ['Cao cấp', 'Tiếp khách', 'Gia đình', 'Tốt cho sức khỏe'],
    note: 'Không gian sang trọng yên tĩnh, nước dùng nấm thanh ngọt đỉnh cao',
    isFavorite: true,
  },
  {
    id: 'food_cafe_giang',
    name: 'Cafe Giảng',
    category: 'coffee_dessert',
    specialtyDishes: 'Cà phê trứng nóng hổi béo ngậy, cacao trứng',
    priceRange: '35.000đ - 55.000đ',
    approxPricePerPerson: 40000,
    address: '39 Nguyễn Hữu Huân, P. Lý Thái Tổ, Q. Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0348,
    longitude: 105.8541,
    openingHours: '07:00 - 22:30',
    rating: 4.8,
    tags: ['Cà phê trứng', 'Phố cổ', 'Check-in'],
    note: 'Cụ Giảng là người sáng tạo món cà phê trứng từ năm 1946',
  },
  {
    id: 'food_comnieu_thuynga',
    name: 'Cơm Niêu Thúy Nga',
    category: 'rice',
    specialtyDishes: 'Cơm niêu cháy giòn, cá bống kho tộ, canh cua cà pháo',
    priceRange: '130.000đ - 250.000đ/người',
    approxPricePerPerson: 180000,
    address: '110B2 Nguyễn Chí Thanh, P. Láng Hạ, Q. Đống Đa, Hà Nội',
    city: 'Hà Nội',
    latitude: 21.0211,
    longitude: 105.8118,
    openingHours: '10:00 - 21:30',
    rating: 4.6,
    tags: ['Cơm gia đình', 'Đỗ xe ô tô', 'Tiếp khách'],
    note: 'Cơm niêu đập cháy 2 mặt thơm giòn rụm, cá kho đậm đà đưa cơm',
  },

  // --- TP. HỒ CHÍ MINH ---
  {
    id: 'food_comtam_baghien',
    name: 'Cơm Tấm Ba Ghiền',
    category: 'rice',
    specialtyDishes: 'Miếng sườn nướng khổng lồ che kín đĩa cơm, chả trứng, bì',
    priceRange: '65.000đ - 110.000đ',
    approxPricePerPerson: 85000,
    address: '84 Đặng Văn Ngữ, Phường 10, Q. Phú Nhuận, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7937,
    longitude: 106.6715,
    openingHours: '07:30 - 21:00',
    rating: 4.8,
    tags: ['Sườn khổng lồ', 'Nổi tiếng', 'Michelin Bib Gourmand'],
    note: 'Sườn ướp mật ong nướng than hoa mềm mọng nước, hương vị đặc trưng Sài Gòn',
    isFavorite: true,
  },
  {
    id: 'food_pho_le',
    name: 'Phở Lệ Nguyễn Trãi',
    category: 'noodles',
    specialtyDishes: 'Phở bò thập cẩm, tái nạm gầu gân bò viên giòn sần sật',
    priceRange: '75.000đ - 95.000đ',
    approxPricePerPerson: 85000,
    address: '415 Nguyễn Trãi, Phường 7, Quận 5, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7554,
    longitude: 106.6698,
    openingHours: '06:00 - 01:00 (đêm)',
    rating: 4.8,
    tags: ['Phở Sài Gòn', 'Ăn đêm', 'Michelin Guide'],
    note: 'Nước dùng ngọt đậm đà từ xương ống hầm kỹ, bò viên tự làm rất ngon',
    isFavorite: true,
  },
  {
    id: 'food_banhmi_huynhhoa',
    name: 'Bánh Mì Huỳnh Hoa',
    category: 'casual',
    specialtyDishes: 'Bánh mì pate bơ chả giò ngập tràn nhân nặng nửa ký',
    priceRange: '65.000đ - 85.000đ',
    approxPricePerPerson: 70000,
    address: '26 Lê Thị Riêng, P. Bến Thành, Quận 1, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7712,
    longitude: 106.6917,
    openingHours: '11:00 - 21:00',
    rating: 4.6,
    tags: ['Bánh mì ô môi', 'Nổi tiếng', 'Siêu nhiều thịt'],
    note: 'Pate béo ngậy quết dày, ăn nửa ổ là no căng bụng',
  },
  {
    id: 'food_pizza_4ps',
    name: "Pizza 4P's Bến Thành",
    category: 'casual',
    specialtyDishes: 'Pizza phô mai Burrata tươi nhà làm, mỳ Ý sốt cua đặc biệt',
    priceRange: '200.000đ - 380.000đ/người',
    approxPricePerPerson: 280000,
    address: '8 Thủ Khoa Huân, P. Bến Thành, Quận 1, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7738,
    longitude: 106.6978,
    openingHours: '10:00 - 22:30',
    rating: 4.9,
    tags: ['Hẹn hò', 'Gia đình', 'Phô mai tươi', 'Dịch vụ chuẩn Nhật'],
    note: 'Nên đặt bàn trước qua ứng dụng hoặc hotline vào cuối tuần',
    isFavorite: true,
  },
  {
    id: 'food_dimtutac',
    name: 'Dim Tu Tac - Ẩm Thực Quảng Đông',
    category: 'fine_dining',
    specialtyDishes: 'Há cảo tôm thủy tinh, xíu mại gạch cua, vịt quay Bắc Kinh',
    priceRange: '250.000đ - 480.000đ/người',
    approxPricePerPerson: 350000,
    address: '29B Trần Cao Vân, Phường 6, Quận 3, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7842,
    longitude: 106.6961,
    openingHours: '10:00 - 22:00',
    rating: 4.8,
    tags: ['Dimsum', 'Tiếp khách', 'Gia đình', 'Đỗ xe thoải mái'],
    note: 'Dimsum tươi nóng hổi nặn tay trong ngày, vị thanh tinh tế chuẩn vị',
  },
  {
    id: 'food_lauga_lae',
    name: 'Lẩu Gà Lá É Tao Ngộ',
    category: 'hotpot_bbq',
    specialtyDishes: 'Lẩu gà đồi lá é cay nồng ớt xiêm xanh & nấm bào ngư',
    priceRange: '180.000đ - 280.000đ/nồi',
    approxPricePerPerson: 120000,
    address: '79 Trần Huy Liệu, Phường 12, Q. Phú Nhuận, TP. HCM',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7915,
    longitude: 106.6782,
    openingHours: '10:00 - 22:00',
    rating: 4.7,
    tags: ['Lẩu ngon', 'Bạn bè tụ tập', 'Hương vị Đà Lạt'],
    note: 'Lá é the cay thơm lừng kích thích vị giác, nước lẩu ngọt thanh từ gà ta',
  },

  // --- ĐÀ NẴNG ---
  {
    id: 'food_miquang_bamua',
    name: 'Mì Quảng Bà Mua',
    category: 'noodles',
    specialtyDishes: 'Mì Quảng ếch, mì Quảng tôm thịt cắn kèm ớt xanh giòn',
    priceRange: '35.000đ - 60.000đ',
    approxPricePerPerson: 45000,
    address: '95A Nguyễn Tri Phương, Q. Thanh Khê, Đà Nẵng',
    city: 'Đà Nẵng',
    latitude: 16.0592,
    longitude: 108.2045,
    openingHours: '06:30 - 21:30',
    rating: 4.7,
    tags: ['Đặc sản Đà Nẵng', 'Rau sống bắp chuối', 'Bánh tráng mè'],
    note: 'Sợi mì vàng óng dai mềm, chan nước nhưn đậm đà vừa phải',
    isFavorite: true,
  },
  {
    id: 'food_banhtrang_tran',
    name: 'Bánh Tráng Cuốn Thịt Heo Đại Lộc - Quán Trần',
    category: 'casual',
    specialtyDishes: 'Thịt heo hai đầu da luộc mỏng cuốn rau rừng & mắm nêm',
    priceRange: '120.000đ - 180.000đ/phần',
    approxPricePerPerson: 150000,
    address: '04 Lê Duẩn, Q. Hải Châu, Đà Nẵng',
    city: 'Đà Nẵng',
    latitude: 16.0718,
    longitude: 108.2212,
    openingHours: '09:00 - 22:00',
    rating: 4.8,
    tags: ['Thịt heo 2 đầu da', 'Mắm nêm trứ danh', 'Máy lạnh'],
    note: 'Đĩa rau sống hơn 10 loại tươi rói, mắm nêm giã tỏi ớt thơm lừng',
  },
];
